rails/helloapp/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  
  get '/hello', to: 'home#hello'

  get '/hello/:id', to: 'home#hello'

  resources :courses do
    member do
      get :do_smth_with_course
      get :do_hard_work
    end
    collection do
      put :do_smth_with_all_courses
      delete :destroy_all
    end
  end
end

rails/helloapp/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= ::User.new
    if user.is_admin?
      can :manage, ::Course
    else
      can :read, ::Course
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

rails/helloapp/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

rails/helloapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/helloapp/app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :students

  validates :name, presence: true, length: { maximum: 30 }

  before_save :do_smth

  def do_smth
    puts 'before save...'
    self.name = "#{self.name} he-he-he"
  end

  def do_other_thing
    puts 'hello'
  end

  def do_hard_work
    puts 'doing smth hard...'
    sleep 10
    puts 'finished'
  end
end

rails/helloapp/app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :students
end

rails/helloapp/app/models/student.rb
class Student < ApplicationRecord
  has_one :record_book, class_name: 'Student::RecordBook'
  belongs_to :faculty
  has_and_belongs_to_many :courses

  def take_exam(course, grade = 0)
    grade > 0 ? 61 : nil
  end
end

rails/helloapp/app/models/student/record_book.rb
class Student::RecordBook < ApplicationRecord
  belongs_to :student
end

rails/helloapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

rails/helloapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    ::I18n.locale = params[:locale]
  end
end

rails/helloapp/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  layout 'courses'
  protect_from_forgery except: %i[update destroy]
  before_action :load_course, only: %i[update destroy edit do_hard_work]
  before_action :authenticate_user!

  def index
    @courses = ::Course.accessible_by(current_ability).includes(:students)
  end

  def destroy
    render json: {success: @course.destroy}
  end

  def update
    authorize! :update, @course
    @course.attributes = course_params
    @course.save
    redirect_to :courses
  end

  def edit
  end

  def do_hard_work
    ::ProcessCourseWorker.perform_async(@course.id)
    render plain: 'processing started...'
  end

  private

  def load_course
    @course = ::Course.find params[:id]
  end

  def course_params
    params.require(:course).permit(:name)
  end
end

rails/helloapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render plain: 'Hello, worlddddd!'
  end

  def hello
    @student = ::Student.find params[:id]
  end
end

rails/helloapp/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/helloapp/app/helpers/courses_helper.rb
module CoursesHelper
end

rails/helloapp/app/views/courses/_course.html.erb
<tr>
  <td><%= course.id %></td>
  <td><%= course.name %></td>
  <td><%= course.students.size %></td>
  <td>
    <%= link_to('Edit', edit_course_path(course.id), class: 'btn btn-warning') if can?(:update, course) %>
    <%= link_to('Process', do_hard_work_course_path(course.id), class: 'btn btn-success') if can?(:update, course) %>
  </td>
</tr>

rails/helloapp/app/views/courses/edit.html.erb
<%= form_for(@course) do |f| %>
  Name: <%= f.text_field :name %>
  <br/><%= f.submit 'Save' %>
<% end %>

rails/helloapp/app/views/courses/index.html.erb
<h1><%= t('ui.courses.title') %></h1>
<table>
  <tr>
    <th>ID</th>
    <th><%= t('ui.courses.columns.name') %></th>
    <th><%= t('ui.courses.columns.students_number') %></th>
    <th><%= t('ui.generic.actions') %></th>
  </tr>
  <% @courses.each do |course| %>
    <%= render partial: 'course', locals: {course: course} %>
  <% end %>
</table>
<div>
  <%= link_to t('ui.courses.new'), new_course_path, class: 'btn btn-primary' %>
</div>

rails/helloapp/app/views/home/hello.html.erb
<% if @student.present? %>
  <h1>Hello, <%= @student.name %>!!</h1>
<% else %>
  <h1>Foo bar</h1>
<% end %>

rails/helloapp/app/views/layouts/_logged_in_user.html.erb
<% if current_user %>
  Logged in as <%= current_user.email %>
<% end %>

rails/helloapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <h1>HelloApp</h1>
    <%= render partial: '/layouts/logged_in_user' %>
    <%= yield %>
  </body>
</html>

rails/helloapp/app/views/layouts/courses.html.erb
<html>
  <head>
    <title>Courses</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'courses' %>
  </head>
  <body>
    <%= image_tag 'ruby.jpeg' %>
    <div class="container-fluid">
      <%= render partial: '/layouts/logged_in_user' %>
      <%= yield %>
    </div>
  </body>
</html>